### ISSUE TITLE
CORS problem！

### ISSUE THREAD

**Issue by RitianWu** [aleen42/gitbook-comments#4]
So happy while seeing your repo, that's what I want!
However, it seems that my gitbook wiki page has a CORS error!

This is my configuration using self-hosted Gitlab:
![image](https://user-images.githubusercontent.com/3898974/76500604-cb225000-647b-11ea-973d-3a834df4d8d2.png)

And this is my error info:
![image](https://user-images.githubusercontent.com/3898974/76500979-729f8280-647c-11ea-90dd-8809f4025f92.png)

**Comment by aleen42** [comment]
GitLab should have set `Access-Control-Allow-Origin: *` header to allow `/api/*` requests, and please check your GitLab version, and I have successfully integrated with **GitLab CE 11.7.5**.

- https://gitlab.com/gitlab-org/gitlab-foss/-/issues/19470
- https://gitlab.com/gitlab-org/gitlab-foss/-/issues/22450
- https://gitlab.com/gitlab-org/gitlab-foss/-/issues/36823

**Comment by aleen42** [comment]
However, there are vulnerabilities of CORS if you host your GitLab in public. Find a way to set up a specified domain in such a case.

**Comment by RitianWu** [comment]
Thanks a lot!!!
While my GitLab version is **GitLab EE 12.7.6**，I will check my GitLab configuration settings.
Thanks your suggestions again.

**Comment by RitianWu** [comment]
> However, there are vulnerabilities of CORS if you host your GitLab in public. Find a way to set up a specified domain in such a case.
